apiVersion: v2
name: metabase
description: The simplest, fastest way to get business intelligence and analytics to everyone in your company
home: http://www.metabase.com/
icon: http://www.metabase.com/images/logo.svg

type: application

version: 1.0.0

appVersion: "latest"

dependencies:
- name: postgresql
  version: ~13.2.10
  repository: https://charts.bitnami.com/bitnami
  condition: postgres.enabled
